language: php

php:
  - 7.1
  - 7.0
  - 5.6

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml || true; fi"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false